### ISSUE TITLE
With active CutterFix Mod the Claas Jaguar75 does not work

### ISSUE THREAD

**Issue by Ulanawius** [4c65736975/cutterFix#2]
Thank you very much for the great work. I really like the CutterFix mod.
Using small equipment on a new game I learned, that the mod "Claas Jaguar 75" does not work together with CutterFix. If CutterFix is active, nothing will be filled into the trailer. If CutterFix is disabled, the Jaguar works - see screenshots.

CutterFix enabled:
![Farming Simulator 22 Screenshot 2023 10 08 - 23 01 57 71](https://github.com/4c65736975/cutterFix/assets/76711921/547c8d7a-1ad7-4188-8f4b-35c905882a6a)
CutterFix disabled:
![Farming Simulator 22 Screenshot 2023 10 08 - 23 03 17 26](https://github.com/4c65736975/cutterFix/assets/76711921/dd02b3c7-4284-493a-a5a3-ebd4c3533558)
No other mods and no errors or warnings in the log.

**Comment by 4c65736975** [comment]
This seems to be due to the way the Jaguar is programmed, as I see in the input help (F1), it cannot be raised or lowered and that seems to be the problem. I'll take a look at it ;)

**Comment by Ulanawius** [comment]
That is right. It lowers the pickup when turning on and lifts it when turning off.

**Comment by 4c65736975** [comment]
The problem could not be reproduced, everything with the "Claas Jaguar 75" modification works properly, the header can be lowered and raised, and the trailer fills properly
